@echo off

set EMMA_HOME=C:\java\emma-2.0.4120

set java_opts=-cp ../bin;%EMMA_HOME%\lib\emma.jar -showversion -Xnoclassgc -da -dsa

:: number of transactions generated by each thread
:: each tx produces two messages, commit and done
set java_opts=%java_opts% -Dxa.msg.count=200

:: message size for the commit record.
:: the done record is much smaller because it includes
:: only the token referring back to the commit
set java_opts=%java_opts% -Dxa.msg.size=80

:: number of worker threads
set java_opts=%java_opts% -Dxa.workers=1200
set java_opts=%java_opts% -Dhowl.log.maxWaitingThreads=9999

:: interval used by force manager thread to sleep
set java_opts=%java_opts% -Dhowl.log.flushSleepTime=50

:: specify buffer size in number of 1024 byte blocks
set java_opts=%java_opts% -Dhowl.log.bufferSize=4
set java_opts=%java_opts% -Dhowl.log.bufferPoolSize=2
set java_opts=%java_opts% -Dhowl.log.maxBlocksPerFile=100
set java_opts=%java_opts% -Dhowl.log.LogFile.maxLogFiles=3
set java_opts=%java_opts% -Dhowl.log.LogFile.dir=../logs
set java_opts=%java_opts% -Dhowl.log.LogFile.filename=xa
set java_opts=%java_opts% -Dhowl.log.LogFile.ext=log
set java_opts=%java_opts% -Dhowl.LogBuffer.class=org.objectweb.howl.log.BlockLogBuffer
set java_opts=%java_opts% -Dhowl.LogBuffer.checksum=true
set java_opts=%java_opts% -Dhowl.log.test.setautomark=true
set java_opts=%java_opts% -Dhowl.log.test.timeStamp=false


set class=org.objectweb.howl.test.LogTest

setlocal
set JAVA_HOME=C:\java\j2sdk1.4.2_04
set mode=1.4

if "%1"=="tiger" (
set JAVA_HOME=C:\java\jdk1.5.0
set mode=1.5
)

if "%1"=="jrocket" (
set JAVA_HOME=C:\java\bea\jrockit81sp2_141_05
set mode=1.4
set PATH=%java_home%\bin;%path%
set java_opts=%java_opts% -Xnoclassgc -Xgc:singlecon
)

if "%1"=="ibm" (
set JAVA_HOME=C:\java\IBM\Java141\jre
set mode=1.4
set PATH=%java_home%\jre\bin;%path%
)

set emma=
if "%1"=="emma" (
set emma=emmarun -r html -sp . -cp ../bin
)

%java_home%\bin\javac -source %mode% -target %mode% -d ../bin -g -sourcepath java java/org/objectweb/howl/test/LogTest.java
%java_home%\bin\java %java_opts% %emma% %class% 
