@echo off

set java_opts=-cp ../classes -showversion

:: number of transactions generated by each thread
:: each tx produces two messages, commit and done
set java_opts=%java_opts% -Dxa.msg.count=50

:: message size for the commit record.
:: the done record is much smaller because it includes
:: only the token referring back to the commit
set java_opts=%java_opts% -Dxa.msg.size=80

:: number of worker threads
set java_opts=%java_opts% -Dxa.workers=800


:: interval used by force manager thread to sleep
set java_opts=%java_opts% -Dhowl.log.flushSleepTime=50

:: specify buffer size in number of 1024 byte blocks
set java_opts=%java_opts% -Dhowl.log.bufferSize=4
set java_opts=%java_opts% -Dhowl.log.bufferPoolSize=32
set java_opts=%java_opts% -Dhowl.log.maxWaitingThreads=500
set java_opts=%java_opts% -Dhowl.LogBuffer.class=org.objectweb.howl.log.BlockLogBuffer
set java_opts=%java_opts% -Dhowl.log.maxBlocksPerFile=200
set java_opts=%java_opts% -Dhowl.log.LogFile.maxLogFiles=3
set java_opts=%java_opts% -Dhowl.log.LogFile.dir=../logs
set java_opts=%java_opts% -Dhowl.log.LogFile.filename=xa
set java_opts=%java_opts% -Dhowl.log.LogFile.ext=log
set java_opts=%java_opts% -Dhowl.log.test.setautomark=true

:: set next parameter false to actually do IO
:: set to true if you want to run with no IO to measure JVM gating
set java_opts=%java_opts% -Dhowl.logbuffer.noforce=false

:: set the full path of the log file.
set java_opts=%java_opts% -Dhowl.log.filename=xa.log

set class=org.objectweb.howl.log.LogTest

setlocal
set JAVA_HOME=C:\java\j2sdk1.4.2_03
set mode=1.4
if "%1"=="tiger" (
set JAVA_HOME=C:\java\j2sdk1.5.0
set mode=1.5
)
%java_home%\bin\javac -source %mode% -target %mode% -d ../classes org/objectweb/howl/log/LogTest.java
%java_home%\bin\java -ea %java_opts% %class%
