/*
 * Created on Mar 26, 2004
 *
 */
package org.objectweb.howl.log;


/**
 * Define record types used by Logger implementations
 * 
 * @author Michael Giroux
 */
public interface LogRecordType
{
  /**
   * Log records generated by user.
   */
  static final short USER   = 0;
  
  /**
   * Log records generated by Logger.
   * <p>must be ORed with another value to form a
   * complete type.
   */
  static final short CTRL   = 0x4000;
  
  /**
   * Log records containing mark data (a log key)
   */
  static final short MARKKEY  = 0x2000;
  
  /**
   * Automark mode for the log.
   * <p>Data portion of record contains 1 if automark
   * is enabled, and 0 if automark is disabled.
   */
  static final short AUTOMARK = 0x1000;
  
  /**
   * Header records generated at start of every log file.
   */
  static final short HEADER = 0x0800;

}
